swagger: "2.0"
info:
  description: "SoluCX - API Documentation"
  version: "1.0.0"
  title: "SoluCX - Test"
host: "localhost"
basePath: "/api"
tags:
  - name: "Clients"
  - name: "Collaborators"
  - name: "Stores"
  - name: "Transactions"
  - name: "Evaluations"
schemes:
  - "http"
paths:
  /clients:
    post:
      tags:
      - "Clients"
      summary: "Add a new client"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Client informations"
        required: true
        schema:
          $ref: "#/definitions/Client_Data"
      responses:
        "201":
          description: "Success"
          schema:
            $ref: "#/definitions/Client"
        "405":
          description: "Invalid input"
    get:
      tags:
      - "Clients"
      summary: "List clients"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/Clients"
	"405":
          description: "Invalid input"
  /clients/{id}:
    put:
      tags:
      - "Clients"
      summary: "Update a client"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: id
        type: integer
        required: true
        description: "Client ID"
      - in: "body"
        name: "body"
        description: "Client Informations"
        required: true
        schema:
          $ref: "#/definitions/Client_Data"
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/Client"
	"404":
          description: "Not Found"
        "405":
          description: "Invalid input"
    delete:
      tags:
      - "Clients"
      summary: "Delete a client"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: id
        type: integer
        required: true
        description: "Client ID"
      responses:
        "204":
          description: "Success"
	"404":
          description: "Not Found"
        "405":
          description: "Invalid input"
          
  /collaborators:
    post:
      tags:
      - "Collaborators"
      summary: "Add a new collaborator"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Collaborator informations"
        required: true
        schema:
          $ref: "#/definitions/Collaborator_Data"
      responses:
        "201":
          description: "Success"
          schema:
            $ref: "#/definitions/Collaborator"
        "405":
          description: "Invalid input"
    get:
      tags:
      - "Collaborators"
      summary: "List collaborators"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/Collaborators"
	"405":
          description: "Invalid input"
  /collaborators/{id}:
    put:
      tags:
      - "Collaborators"
      summary: "Update a collaborator"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: id
        type: integer
        required: true
        description: "Collaborator ID"
      - in: "body"
        name: "body"
        description: "Collaborator Informations"
        required: true
        schema:
          $ref: "#/definitions/Collaborator_Data"
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/Collaborator"
	"404":
          description: "Not Found"
        "405":
          description: "Invalid input"
    delete:
      tags:
      - "Collaborators"
      summary: "Delete a collaborator"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: id
        type: integer
        required: true
        description: "Collaborator ID"
      responses:
        "204":
          description: "Success"
        "404":
          description: "Not Found"
	"405":
          description: "Invalid input"
          
  /stores:
    post:
      tags:
      - "Stores"
      summary: "Add a new store"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Store informations"
        required: true
        schema:
          $ref: "#/definitions/Store_Data"
      responses:
        "201":
          description: "Success"
          schema:
            $ref: "#/definitions/Store"
        "405":
          description: "Invalid input"
    get:
      tags:
      - "Stores"
      summary: "List stores"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/Stores"
	"405":
          description: "Invalid input"
  /stores/{id}:
    put:
      tags:
      - "Stores"
      summary: "Update a store"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: id
        type: integer
        required: true
        description: "Store ID"
      - in: "body"
        name: "body"
        description: "Store Informations"
        required: true
        schema:
          $ref: "#/definitions/Store_Data"
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/Store"
	"404":
          description: "Not Found"
        "405":
          description: "Invalid input"
    delete:
      tags:
      - "Stores"
      summary: "Delete a Store"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: id
        type: integer
        required: true
        description: "Store ID"
      responses:
        "204":
          description: "Success"
        "404":
          description: "Not Found"
	"405":
          description: "Invalid input"
          
  /transactions:
    post:
      tags:
      - "Transactions"
      summary: "Add a new transaction"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Transaction informations"
        required: true
        schema:
          $ref: "#/definitions/Transaction_Data"
      responses:
        "201":
          description: "Success"
          schema:
            $ref: "#/definitions/Transaction"
        "405":
          description: "Invalid input"
  /transactions/{id}:
    put:
      tags:
      - "Transactions"
      summary: "Update a transaction"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: id
        type: integer
        required: true
        description: "Transaction ID"
      - in: "body"
        name: "body"
        description: "Transaction Informations"
        required: true
        schema:
          $ref: "#/definitions/Transaction_Data"
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/Transaction"
        "404":
          description: "Not Found"
	"405":
          description: "Invalid input"
          
  /evaluations:
    post:
      tags:
      - "Evaluations"
      summary: "Add a new evaluation"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Evaluation informations"
        required: true
        schema:
          $ref: "#/definitions/Evaluation_Data"
      responses:
        "201":
          description: "Success"
          schema:
            $ref: "#/definitions/Evaluation"
        "405":
          description: "Invalid input"
    get:
      tags:
      - "Evaluations"
      summary: "List evaluations"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/Evaluations"
        "405":
          description: "Invalid input"
definitions:
  #Models
  Client:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
        example: "Client"
      email:
        type: "string"
        example: "client@email.com"
      phone:
        type: "string"
        example: "(11) 9999-99999"
      document:
        type: "string"
        example: "999.999.999-99"
  Collaborator:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
        example: "Collaborator"
  Store:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
        example: "Store"
  Transaction:
    type: "object"
    properties:
      id:
        type: "integer"
      client:
        $ref: "#/definitions/Client"
      store:
        $ref: "#/definitions/Store"
      collaborator:
        $ref: "#/definitions/Collaborator"
      date:
        type: "integer"
        example: "2021-03-11"
      value:
        type: "number"
        example: "209.32"
  Evaluation:
    type: "object"
    properties:
      id:
        type: "integer"
      transaction:
        $ref: "#/definitions/Transaction"
      grade:
        type: "integer"
        example: "10"
      comment:
        type: "string"
        example: "Comment about the transaction experience"
        
  #Data
  Client_Data:
    type: "object"
    required:
    - "name"
    - "email"
    - "phone"
    - "document"
    properties:
      name:
        type: "string"
        example: "Client"
      email:
        type: "string"
        example: "client@email.com"
      phone:
        type: "string"
        example: "(11) 9999-99999"
      document:
        type: "string"
        example: "999.999.999-99"
  Collaborator_Data:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
        example: "Collaborator"
  Store_Data:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
        example: "Store"
  Transaction_Data:
    type: "object"
    required:
    - "client_id"
    - "date"
    - "value"
    properties:
      client_id:
        type: "integer"
        example: "1"
      store_id:
        type: "integer"
        example: "1"
      collaborator_id:
        type: "integer"
        example: "1"
      date:
        type: "integer"
        example: "2021-03-11"
      value:
        type: "number"
        example: "209.32"
  Evaluation_Data:
    type: "object"
    required:
    - "transaction_id"
    - "grade"
    properties:
      transaction_id:
        type: "integer"
        example: "1"
      grade:
        type: "integer"
        example: "10"
      comment:
        type: "string"
        example: "Comment about the transaction experience"
        
  #Collections
  Clients:
    type: array
    items:
      $ref: "#/definitions/Client"
  Collaborators:
    type: array
    items:
      $ref: "#/definitions/Collaborator"
  Stores:
    type: array
    items:
      $ref: "#/definitions/Store"
  Transactions:
    type: array
    items:
      $ref: "#/definitions/Transaction"
  Evaluations:
    type: array
    items:
      $ref: "#/definitions/Evaluation"
